import { z } from "zod";
import type { AppEntry } from "./apps.ts";
import { readManifestFile } from "./apps.ts";

/**
 * CODEOWNERS generation: each app's maintainers own
 * `/apps/<slug>/`, so they approve bumps to their app.
 *
 * Reads only `slug` and `maintainers`, with a local schema, so it runs without an
 * appflare checkout; full manifest validation is `pnpm validate`.
 */

/** A GitHub user (`name`) or team (`org/team`), optionally written with a leading `@`. */
const ownerSchema = z
  .string()
  .regex(
    /^@?[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})(?:\/[A-Za-z0-9._-]+)?$/,
    "must be a GitHub user or org/team",
  );

const ownershipSchema = z.object({
  slug: z.string().min(1),
  maintainers: z.array(ownerSchema).min(1),
});
export type Ownership = z.infer<typeof ownershipSchema>;

export const CODEOWNERS_HEADER = `# Generated by scripts/gen-codeowners.ts from each app's "maintainers".
# Do not edit by hand: run \`pnpm gen-codeowners\`.
`;

/** Reads `slug` and `maintainers` from each app's manifest. */
export function readOwnership(apps: readonly AppEntry[]): Ownership[] {
  return apps.map((app) => {
    const result = ownershipSchema.safeParse(readManifestFile(app.manifestPath));
    if (!result.success) {
      throw new Error(`${app.manifestPath}: ${z.prettifyError(result.error)}`);
    }
    if (result.data.slug !== app.slug) {
      throw new Error(`${app.manifestPath}: slug must match its folder name "${app.slug}"`);
    }
    return result.data;
  });
}

/** Renders CODEOWNERS: one `/apps/<slug>/ @owner…` line per app, in slug order. */
export function renderCodeowners(owners: readonly Ownership[]): string {
  const lines = [...owners]
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map((o) => {
      const handles = [...new Set(o.maintainers.map((m) => `@${m.replace(/^@/, "")}`))];
      return `/apps/${o.slug}/ ${handles.join(" ")}`;
    });
  return `${CODEOWNERS_HEADER}\n${lines.join("\n")}\n`;
}
