import { appendFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parseArgs } from "node:util";
import { Resvg } from "@resvg/resvg-js";
import { findApp, readManifestFile } from "./lib/apps.ts";
import { info, runMain } from "./lib/cli.ts";
import { coverSvg, iconSvg } from "./lib/cover-art.ts";
import { MEDIA_SOURCES_FILE } from "./lib/media.ts";
import { appsDir } from "./lib/paths.ts";

const USAGE = `Usage: pnpm gen-media <slug>... [--icon] [--cover] [--force]

Makes the images an entry is missing, for entries whose upstream repository
has no icon or cover the catalog may use:
  apps/<slug>/icon.png    512x512 monogram of the name
  apps/<slug>/cover.png   1200x630: the name, the summary, the upstream
                          repository, and the entry's icon when it has one
and records each generated file in apps/<slug>/MEDIA.md.

Without --icon or --cover, makes whichever of the two is missing. An existing
file is only replaced with --force. Text is set in the first installed font of
Inter, Open Sans, Noto Sans, DejaVu Sans, so regenerating on another machine
may change the glyphs slightly.
`;

function render(svg: string): Buffer {
  const resvg = new Resvg(svg, {
    fitTo: { mode: "original" },
    font: { loadSystemFonts: true, defaultFontFamily: "Open Sans" },
  });
  return Buffer.from(resvg.render().asPng());
}

/** The entry's current icon as a data URI, for the cover. */
function iconDataUri(dir: string): string | undefined {
  const svg = path.join(dir, "icon.svg");
  if (existsSync(svg)) {
    return `data:image/svg+xml;base64,${readFileSync(svg).toString("base64")}`;
  }
  const png = path.join(dir, "icon.png");
  if (existsSync(png)) {
    return `data:image/png;base64,${readFileSync(png).toString("base64")}`;
  }
  return undefined;
}

/** Adds a line for `file` to MEDIA.md unless the file is already named there. */
function recordSource(dir: string, file: string, what: string): void {
  const sources = path.join(dir, MEDIA_SOURCES_FILE);
  const current = existsSync(sources) ? readFileSync(sources, "utf8") : "";
  if (current.includes(`\`${file}\``)) return;
  const header = current === "" ? "# Image sources\n\n" : current.endsWith("\n") ? "" : "\n";
  appendFileSync(
    sources,
    `${header}- \`${file}\`: generated by \`scripts/gen-media.ts\` from ${what}.\n`,
  );
}

runMain(() => {
  const { values, positionals } = parseArgs({
    allowPositionals: true,
    options: {
      icon: { type: "boolean" },
      cover: { type: "boolean" },
      force: { type: "boolean" },
      help: { type: "boolean", short: "h" },
    },
  });
  if (values.help || positionals.length === 0) {
    process.stdout.write(USAGE);
    return values.help ? 0 : 1;
  }
  const chosen = values.icon === true || values.cover === true;
  for (const slug of positionals) {
    const app = findApp(appsDir, slug);
    const manifest = readManifestFile(app.manifestPath) as {
      name: string;
      summary: string;
      repo: string;
    };
    const hasIcon = ["icon.svg", "icon.png"].some((f) => existsSync(path.join(app.dir, f)));
    const wantIcon = chosen ? values.icon === true : !hasIcon;
    if (wantIcon) {
      if (hasIcon && values.force !== true) {
        throw new Error(`${slug}: already has an icon; pass --force to replace it`);
      }
      writeFileSync(path.join(app.dir, "icon.png"), render(iconSvg({ slug, name: manifest.name })));
      recordSource(app.dir, "icon.png", "the name");
      info(`${slug}: wrote icon.png`);
    }
    const coverPath = path.join(app.dir, "cover.png");
    const wantCover = chosen ? values.cover === true : !existsSync(coverPath);
    if (wantCover) {
      if (existsSync(coverPath) && values.force !== true) {
        throw new Error(`${slug}: already has cover.png; pass --force to replace it`);
      }
      const svg = coverSvg({
        slug,
        name: manifest.name,
        summary: manifest.summary,
        repo: manifest.repo,
        iconDataUri: iconDataUri(app.dir),
      });
      writeFileSync(coverPath, render(svg));
      recordSource(app.dir, "cover.png", "the name, summary and repository (with the icon)");
      info(`${slug}: wrote cover.png`);
    }
  }
  return 0;
});
